### ISSUE TITLE
How to make Copytranslator run on the left of the screen?

### ISSUE THREAD

**Issue by Sun-Pengcheng** [Andy-AO/CopytranslatorAppBar#1]
Hello, developer! Is there a parameter to change the location of Copytranlator? I want to run it on the left of the screen? Thanks very much. It helps me a lot.

**Comment by Andy-AO** [comment]
![image](https://user-images.githubusercontent.com/38101170/144761427-0bb61fad-8ddd-4842-a75f-beb2b159833f.png)

`uEdge=0`

**Comment by Sun-Pengcheng** [comment]
> ![image](https://user-images.githubusercontent.com/38101170/144761427-0bb61fad-8ddd-4842-a75f-beb2b159833f.png)
> 
> `uEdge=0`

Thanks a lot for your reply! I am a green hand. I tried to run the AppBar with your BeanLib package, but an error occurred as "Core\Bean.ahk" cannot be opened. I tried to run the file "Bean.ahk", and an error showed as: 
    Call to nonexistent function. 
    Line 033: theTypeString := Type.ofCode(Type(aObj)).
My operating system is of Windows 10 19044.1387, 21H2, x64. And AutoHotkey version is 1.1.33.10. Does it mean I should include some libraries? Or just change my version?

**Comment by Andy-AO** [comment]
AutoHotKey is a poorly designed language, and that BeanLib is something I built myself when I first learned to program, so it's normal that it doesn't work well. In fact, I don't use them much anymore. I feel that something like AutoHotKey would be much better implemented in C# or Python.

AutoHotKey has no stack trace by default, which leads to not knowing what's going on at all. I think I can add this setting to the configuration file for you, and then you don't have to modify the original code, you can just modify that configuration file.

**Comment by Andy-AO** [comment]
Yes, there is no reliable unit test for this language, let alone continuous integration. Maybe that thing can only run on my computer……

**Comment by Andy-AO** [comment]
The new version has been released. You can change the location in the configuration file.

**Comment by Sun-Pengcheng** [comment]
Thank you very much! 
I can't run the source code to convert it into an exe program.
Could you help me by providing the exe version?


Best,
Pengcheng










At 2021-12-07 07:17:57, "Andy AO" ***@***.***> wrote:

Closed #1.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Andy-AO** [comment]
@Sun-Pengcheng  https://github.com/Andy-AO/CopytranslatorAppBar/releases/tag/v0.2

**Comment by Sun-Pengcheng** [comment]
You are so kind! It works. Thanks very much!

从 Windows 版邮件发送

发件人: Andy AO
发送时间: 2021年12月7日 16:00
收件人: Andy-AO/CopytranslatorAppBar
抄送: Sun-Pengcheng; Mention
主题: Re: [Andy-AO/CopytranslatorAppBar] How to make Copytranslator run onthe left of the screen? (Issue #1)

@Sun-Pengcheng https://github.com/Andy-AO/CopytranslatorAppBar/releases/tag/v0.2
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
